### Puxar base de dados

In [1]:
import pandas as pd

tabela = pd.read_csv('exportacoes_franca.csv')
display(tabela)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
1,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),79360,14150
2,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
3,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",European Union (EU),69412,9385
4,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
...,...,...,...,...,...,...,...,...,...,...,...
142355,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",European Union (EU),2316,4
142356,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
142357,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,European Union (EU),27060,26400
142358,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045
142359,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,European Union (EU),31111,23045

### Informações Gerais

Quantas linhas têm a tabela? Existe algum valor vazio que deveria ser tratado?

In [3]:
display(tabela.info())

<class 'pandas.DataFrame'>
RangeIndex: 142360 entries, 0 to 142359
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Year             142360 non-null  int64
 1   Month            142360 non-null  int64
 2   Country          142360 non-null  str
 3   City             142360 non-null  str
 4   SH4 Code         142360 non-null  int64
 5   SH4 Description  142360 non-null  str
 6   SH2 Code         142360 non-null  int64
 7   SH2 Description  142360 non-null  str
 8   Economic Block   142360 non-null  str
 9   US$ FOB          142360 non-null  int64
 10  Net Weight       142360 non-null  int64
dtypes: int64(6), str(5)
memory usage: 11.9 MB

None

In [13]:
#Função de formatação

def formatar(valor):
    valor_formatado = f'US${valor:,.2f}'
    return valor_formatado

### Como foi a evolução das exportações para a frança ao longo dos anos?

Crie uma tabela com os anos de 2016, 2017, 2018, 2019 e 2020 e o valor US$ de exportações

In [14]:
tabela_anos = tabela[["Year", "US$ FOB"]].groupby("Year").sum()
tabela_anos = tabela_anos['US$ FOB'].apply(formatar)
display(tabela_anos)

Year
2016    US$4,615,500,082.00
2017    US$4,448,705,456.00
2018    US$5,239,424,416.00
2019    US$5,218,723,612.00
2020    US$3,967,594,810.00
Name: US$ FOB, dtype: str

### Quais os produtos mais exportados ao longo de todo o período?

Queremos saber os produtos com maior valor US$ de exportação

In [6]:
produtos_exportados = tabela[["SH2 Description","US$ FOB"]].groupby("SH2 Description").sum()
produtos_exportados = produtos_exportados.sort_values(by='US$ FOB', ascending=False)
display(produtos_exportados)

                                                       US$ FOB
SH2 Description
Residues and waste from the food industries; ot...  5641498484
Ores, slag and ash                                  3404353274
Nuclear reactors, boilers, machinery and mechan...  1889781694
Pulp of wood or of other fibrous cellulosic mat...  1855424642
Aircraft, spacecraft, and parts thereof             1253007710
...                                                        ...
Umbrellas, sun umbrellas, walking-sticks, seat-...       18872
Cork and articles of cork                                10974
Wool, fine or coarse animal hair; horsehair yar...        2540
Tin and articles thereof                                  2460
Photographic or cinematographic goods                      148

[97 rows x 1 columns]

### Em 2020 qual cidade mais exportou para a França?
Em valores US$

In [12]:
condicao = tabela['Year']==2020
export_2020 = tabela.loc[condicao,:]
tabela_cidades = export_2020[['City', 'US$ FOB']].groupby("City").sum()
tabela_cidades = tabela_cidades.sort_values(by='US$ FOB', ascending=False)
display(tabela_cidades)

                               US$ FOB
City
Duque de Caxias - RJ         279405596
Luís Eduardo Magalhães - BA  265328132
Ponta Grossa - PR            187777016
São José dos Campos - SP     172939276
Rio de Janeiro - RJ          122522214
...                                ...
Não-Me-Toque - RS                   42
Cubatão - SP                        40
Holambra - SP                       10
São Sebastião do Caí - RS            6
Quatro Pontes - PR                   0

[648 rows x 1 columns]

### Quais os produtos mais exportados (em US$) que as 2 maiores cidades (em exportação em 2020) exportaram?

In [16]:
for i,cidade in enumerate(tabela_cidades.index):
    if i == 2:
        break

    tabela_cidade = export_2020.loc[export_2020['City']==cidade,:]
    tabela_produtos_cidade = tabela_cidade[['SH2 Description','US$ FOB']].groupby('SH2 Description').sum()
    tabela_produtos_cidade = tabela_produtos_cidade.sort_values('US$ FOB', ascending=False)
    print(f"Exportações da cidade {cidade}:")
    display(tabela_produtos_cidade)

Exportações da cidade Duque de Caxias - RJ:

                                                      US$ FOB
SH2 Description
Nuclear reactors, boilers, machinery and mechan...  185816982
Mineral fuels, mineral oils, bituminous substan...   67355688
Articles of iron or steel                             9118714
Residues and waste from the food industries; ot...    4014274
Optical, photographic, cinematographic instrume...    3013092
Nickel and articles thereof                           2951286
Electrical machinery and equipment and parts th...    2595048
Lead and articles thereof                             1660180
Rubber and articles thereof                           1379296
Organic chemicals                                      535136
Vehicles other than railway or tramway rolling-...     353958
Plastics and articles thereof                          228638
Aluminium and articles thereof                         168522
Copper and articles thereof                            138466
Tools, implements, cutlery, spoons and forks, o...      33864
Articles of stone, plaster, cement, asbestos, m...      16856
Miscellaneous chemical products                         11984
Glass and glassware                                      8430
Railway or tramway locomotives, rolling-stock a...       3666
Paper and paperboard; articles of paper pulp, o...       1516

Exportações da cidade Luís Eduardo Magalhães - BA:

                                                      US$ FOB
SH2 Description
Residues and waste from the food industries; ot...  265299808
Edible fruit and nuts; peel of citrus fruits or...      28324